#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
# autospec version: v12
# autospec commit: ec1f7c2
#
Name     : netavark
Version  : 1.11.0
Release  : 2
URL      : https://github.com/containers/netavark/archive/refs/tags/v1.11.0.tar.gz
Source0  : https://github.com/containers/netavark/archive/refs/tags/v1.11.0.tar.gz
Source1  : https://github.com/containers/netavark/releases/download/v1.11.0/netavark-v1.11.0-vendor.tar.gz
Summary  : OCI network stack
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause BSL-1.0 ICU MIT Unicode-DFS-2016 Unlicense Zlib
Requires: netavark-libexec = %{version}-%{release}
Requires: netavark-license = %{version}-%{release}
Requires: netavark-man = %{version}-%{release}
Requires: netavark-services = %{version}-%{release}
BuildRequires : golang-github-cpuguy83-go-md2man
BuildRequires : protobuf
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# netavark: A container network stack
Netavark is a rust based network stack for containers.  It is being designed
to work with [Podman](https://github.com/containers/podman) but is also applicable
for other OCI container management applications.

%package libexec
Summary: libexec components for the netavark package.
Group: Default
Requires: netavark-license = %{version}-%{release}

%description libexec
libexec components for the netavark package.


%package license
Summary: license components for the netavark package.
Group: Default

%description license
license components for the netavark package.


%package man
Summary: man components for the netavark package.
Group: Default

%description man
man components for the netavark package.


%package services
Summary: services components for the netavark package.
Group: Systemd services
Requires: systemd

%description services
services components for the netavark package.


%prep
%setup -q -n netavark-1.11.0
cd %{_builddir}
tar xf %{_sourcedir}/netavark-v1.11.0-vendor.tar.gz
cd %{_builddir}/netavark-1.11.0
mkdir -p ./vendor
cp -r %{_builddir}/vendor/* %{_builddir}/netavark-1.11.0/./vendor
## copy_prepend content
mkdir -p .cargo
cat << EOF > .cargo/config.toml
[source.crates-io]
replace-with = "vendored-sources"
[source.vendored-sources]
directory = "vendor"
EOF
## copy_prepend end

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719619806
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
make  %{?_smp_mflags}


%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719619806
rm -rf %{buildroot}
## install_prepend content
export PREFIX=/usr
make docs
## install_prepend end
mkdir -p %{buildroot}/usr/share/package-licenses/netavark
cp %{_builddir}/netavark-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/netavark/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/vendor/aho-corasick/COPYING %{buildroot}/usr/share/package-licenses/netavark/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/vendor/aho-corasick/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/vendor/aho-corasick/UNLICENSE %{buildroot}/usr/share/package-licenses/netavark/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/vendor/anstream/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/anstream/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/vendor/anstyle-parse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/vendor/anstyle-parse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/64a8c11fd0f3068e743bfc681bcbef4f50a6b779 || :
cp %{_builddir}/vendor/anstyle-query/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/anstyle-query/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/vendor/anstyle/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/anstyle/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/f911b0506e6ba6a56b4edac717b461799f380ef0 || :
cp %{_builddir}/vendor/anyhow/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/anyhow/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/arrayvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/arrayvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/1ed710abaa8e6f1039a65ee19db6b19804514a75 || :
cp %{_builddir}/vendor/async-broadcast/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/3389b1fc45edfdd16c95926164ecf61e8369c9d8 || :
cp %{_builddir}/vendor/async-broadcast/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/2df5d31b2f1da55a1d251084b2b47afe37eb9dde || :
cp %{_builddir}/vendor/async-channel/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/async-channel/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/async-executor/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/async-executor/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/async-fs/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/async-fs/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/async-io-1.13.0/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/async-io-1.13.0/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/async-lock-2.8.0/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/async-lock-2.8.0/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/async-recursion/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/b95542c0be3bd915a1e7d8df80711fce5cd0795b || :
cp %{_builddir}/vendor/async-recursion/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/a74c5e048f9ed570eb892f81ca5daf05936475b0 || :
cp %{_builddir}/vendor/async-stream-impl/LICENSE %{buildroot}/usr/share/package-licenses/netavark/c5880598f02535f99de9ec3436bf8b59ce893bc7 || :
cp %{_builddir}/vendor/async-stream/LICENSE %{buildroot}/usr/share/package-licenses/netavark/c5880598f02535f99de9ec3436bf8b59ce893bc7 || :
cp %{_builddir}/vendor/async-task/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/async-task/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/async-trait/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/async-trait/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/atomic-waker/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/atomic-waker/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/atomic-waker/LICENSE-THIRD-PARTY %{buildroot}/usr/share/package-licenses/netavark/709be9d07c00197f2e96593f4cd84f975c4e9f5f || :
cp %{_builddir}/vendor/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/vendor/axum-core/LICENSE %{buildroot}/usr/share/package-licenses/netavark/4f399d285a128de165a3adb6319e7c85d2a9e297 || :
cp %{_builddir}/vendor/axum/LICENSE %{buildroot}/usr/share/package-licenses/netavark/3175cda277cf92d21d9adbacdcfbf53a02c78890 || :
cp %{_builddir}/vendor/base64/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/base64/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/b716916e6b0b96af5ecadf1eaee25f966f5d6cb2 || :
cp %{_builddir}/vendor/bitflags-1.3.2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/bitflags-1.3.2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/vendor/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/vendor/block-buffer/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/422e6fd980775f9997ed6735c28a14ad20c222e8 || :
cp %{_builddir}/vendor/block-buffer/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/aca18f6eebf597377e59fff1f0e6adbadcdcf97b || :
cp %{_builddir}/vendor/blocking/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/blocking/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/byteorder/COPYING %{buildroot}/usr/share/package-licenses/netavark/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/vendor/byteorder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/vendor/byteorder/UNLICENSE %{buildroot}/usr/share/package-licenses/netavark/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/vendor/bytes/LICENSE %{buildroot}/usr/share/package-licenses/netavark/2510927d07430a2092720e8f4a5287043f75e8d3 || :
cp %{_builddir}/vendor/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/vendor/cfg_aliases/LICENSE %{buildroot}/usr/share/package-licenses/netavark/39806df76979277073594a0c19005c3c7fb17221 || :
cp %{_builddir}/vendor/chrono/LICENSE.txt %{buildroot}/usr/share/package-licenses/netavark/c145b1a607ecf06aed81f1d04a65c2e43dffdc63 || :
cp %{_builddir}/vendor/clap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/clap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/vendor/clap_builder/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/vendor/clap_builder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/vendor/clap_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/vendor/clap_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/vendor/clap_lex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/vendor/clap_lex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/vendor/colorchoice/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/colorchoice/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/vendor/concurrent-queue/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/concurrent-queue/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/cpufeatures/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/422e6fd980775f9997ed6735c28a14ad20c222e8 || :
cp %{_builddir}/vendor/cpufeatures/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/388871ab0ab7f8ba6aaa0d444a5153f15c918cdb || :
cp %{_builddir}/vendor/crossbeam-utils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/crossbeam-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/vendor/crypto-common/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/422e6fd980775f9997ed6735c28a14ad20c222e8 || :
cp %{_builddir}/vendor/crypto-common/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/7ca2c807379211b3ca6b04f10723088ca423c4fe || :
cp %{_builddir}/vendor/data-encoding/LICENSE %{buildroot}/usr/share/package-licenses/netavark/7963d112b803d110d3e75e932c052284fd208629 || :
cp %{_builddir}/vendor/derivative/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/derivative/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/bb7a734916fe2261aa2b805e19a75838d557af9d || :
cp %{_builddir}/vendor/dhcproto/LICENSE %{buildroot}/usr/share/package-licenses/netavark/246a6a647fc03a8acf28b902ab37764142bc0c9c || :
cp %{_builddir}/vendor/digest/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/422e6fd980775f9997ed6735c28a14ad20c222e8 || :
cp %{_builddir}/vendor/digest/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/9c6e81caeb170dd5501d39895df9efb657c3c86b || :
cp %{_builddir}/vendor/either/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/either/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/vendor/enum-as-inner-0.5.1/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/enum-as-inner-0.5.1/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/c71b43677c4ac8205f6eb573a073ea8e6df60c91 || :
cp %{_builddir}/vendor/enum-as-inner/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/enum-as-inner/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/c71b43677c4ac8205f6eb573a073ea8e6df60c91 || :
cp %{_builddir}/vendor/enumflags2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/8e73926030e5cf210703bbdbd4d5c2a3880b3f71 || :
cp %{_builddir}/vendor/enumflags2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/a2e7dc468fde32fb02ccb9417b5bad304836e267 || :
cp %{_builddir}/vendor/enumflags2_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/7c85e3e83cb61889208968604b387fbd188d49c7 || :
cp %{_builddir}/vendor/enumflags2_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/8aa7ac03b16828b3c2263f4d760a779a32d5dd2a || :
cp %{_builddir}/vendor/env_filter/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/env_filter/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/vendor/env_logger/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/env_logger/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/vendor/equivalent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/equivalent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/c371f0a7cbb203643d88566665a452f96bf1ab86 || :
cp %{_builddir}/vendor/errno/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/errno/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/7a842f34e127456338641b14c7a00ec246d89fb6 || :
cp %{_builddir}/vendor/etherparse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/58853eb8199b5afe72a73a25fd8cf8c94285174b || :
cp %{_builddir}/vendor/etherparse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/a3164f0a981565d3d4dbedfbba23fec2bf387a7e || :
cp %{_builddir}/vendor/ethtool/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/bebecee44e7243ae0c5e0971cd4492ba1a19e5cd || :
cp %{_builddir}/vendor/event-listener-2.5.3/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/event-listener-2.5.3/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/event-listener-strategy/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/event-listener-strategy/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/event-listener/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/event-listener/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/fastrand-1.9.0/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/fastrand-1.9.0/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/fastrand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/fastrand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/fixedbitset/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/fixedbitset/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/0c160db99de1b5577d1160540f1a1312b01a3f5b || :
cp %{_builddir}/vendor/fnv/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/fnv/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/50121d8b8c9f6483fe17ea679f28f85fe59b2a5a || :
cp %{_builddir}/vendor/form_urlencoded/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/form_urlencoded/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/738188f5fed28a950b0fede659706238ec35f8bb || :
cp %{_builddir}/vendor/fs2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/fs2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/vendor/futures-channel/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/vendor/futures-channel/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/vendor/futures-core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/vendor/futures-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/vendor/futures-executor/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/vendor/futures-executor/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/vendor/futures-io/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/vendor/futures-io/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/vendor/futures-lite-1.13.0/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/futures-lite-1.13.0/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/futures-lite-1.13.0/LICENSE-THIRD-PARTY %{buildroot}/usr/share/package-licenses/netavark/709be9d07c00197f2e96593f4cd84f975c4e9f5f || :
cp %{_builddir}/vendor/futures-lite/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/futures-lite/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/futures-lite/LICENSE-THIRD-PARTY %{buildroot}/usr/share/package-licenses/netavark/709be9d07c00197f2e96593f4cd84f975c4e9f5f || :
cp %{_builddir}/vendor/futures-macro/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/vendor/futures-macro/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/vendor/futures-sink/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/vendor/futures-sink/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/vendor/futures-task/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/vendor/futures-task/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/vendor/futures-util/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/vendor/futures-util/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/vendor/futures/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/e81567c196622efa36b46c5fd53cde741aaf0993 || :
cp %{_builddir}/vendor/futures/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/067f31555f328efb78075174add7db97d98618c6 || :
cp %{_builddir}/vendor/generic-array/LICENSE %{buildroot}/usr/share/package-licenses/netavark/cb74eb831db08b7fe98f84b59c9bda195e5a3588 || :
cp %{_builddir}/vendor/genetlink/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/bebecee44e7243ae0c5e0971cd4492ba1a19e5cd || :
cp %{_builddir}/vendor/getrandom/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/vendor/getrandom/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/c8eef3d34d69b1d62fd378fa02150a0bce62fd26 || :
cp %{_builddir}/vendor/h2/LICENSE %{buildroot}/usr/share/package-licenses/netavark/072741b191e599c01d8136fd14030bdcdb906e62 || :
cp %{_builddir}/vendor/hashbrown-0.12.3/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/hashbrown-0.12.3/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a || :
cp %{_builddir}/vendor/hashbrown/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/hashbrown/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a || :
cp %{_builddir}/vendor/heck-0.4.1/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/heck-0.4.1/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/vendor/heck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/heck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/vendor/hex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/hex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/b916da18877fcec3d37860fe60c1189c447e90b9 || :
cp %{_builddir}/vendor/http-body/LICENSE %{buildroot}/usr/share/package-licenses/netavark/8e75077dab38548245db65153967207be8c3ce88 || :
cp %{_builddir}/vendor/http/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/ebc84230d16898593f0c90479ac9ee5576d7cc65 || :
cp %{_builddir}/vendor/http/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/fa284d19a6ac85562019f93110d4338e53de654b || :
cp %{_builddir}/vendor/httparse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/httparse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/1de935a6c7ea6a2196a49062d498cb04a7f5baea || :
cp %{_builddir}/vendor/httpdate/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/1726596c1cc6c65d3a272abc337b13936430cf96 || :
cp %{_builddir}/vendor/httpdate/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/f516ded20090880b5bb281ad2f9dde3d94e9e369 || :
cp %{_builddir}/vendor/humantime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/humantime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ff432d95fdfee3587e45abd61685c2209d245901 || :
cp %{_builddir}/vendor/hyper-timeout/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/hyper-timeout/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/0af21fe114d277c00d6ec7fba71f83fc03275b0a || :
cp %{_builddir}/vendor/hyper/LICENSE %{buildroot}/usr/share/package-licenses/netavark/f8cc03f90ea18587a80a23486a64f129260a3034 || :
cp %{_builddir}/vendor/iana-time-zone/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/ff44b187892fcf1cd15a3ca61b498041b28afecc || :
cp %{_builddir}/vendor/iana-time-zone/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/d3f4001d9de83a122956c9195d73e2507bf6c533 || :
cp %{_builddir}/vendor/idna-0.2.3/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/idna-0.2.3/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/738188f5fed28a950b0fede659706238ec35f8bb || :
cp %{_builddir}/vendor/idna/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/idna/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/a81399b7c3ec2d4619848fd59c11d21211fc3b86 || :
cp %{_builddir}/vendor/indexmap-1.9.3/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/indexmap-1.9.3/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/7e5936a6fa3cf3518c01cec41345adf27399fe12 || :
cp %{_builddir}/vendor/indexmap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/indexmap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/7e5936a6fa3cf3518c01cec41345adf27399fe12 || :
cp %{_builddir}/vendor/io-lifetimes/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/io-lifetimes/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/netavark/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/vendor/io-lifetimes/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/ipnet/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/bb92c62835916e922667b4fe181beed0e6efca91 || :
cp %{_builddir}/vendor/ipnet/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/4f8ab673f6e2ae6c7bb2910d7f38838c18c12178 || :
cp %{_builddir}/vendor/iptables/LICENSE %{buildroot}/usr/share/package-licenses/netavark/90b909b5333c24d88b46437677e159fb35e56fad || :
cp %{_builddir}/vendor/is_terminal_polyfill/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/is_terminal_polyfill/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/vendor/itertools/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/itertools/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/vendor/itoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/itoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/lazy_static/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/lazy_static/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/vendor/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/vendor/linux-raw-sys-0.3.8/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/linux-raw-sys-0.3.8/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/netavark/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/vendor/linux-raw-sys-0.3.8/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/linux-raw-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/linux-raw-sys/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/netavark/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/vendor/linux-raw-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/vendor/matches/LICENSE %{buildroot}/usr/share/package-licenses/netavark/1b0e913d41a66c988376898aa995d6c2f45bb50c || :
cp %{_builddir}/vendor/matchit/LICENSE %{buildroot}/usr/share/package-licenses/netavark/84da196f153d2d4e6a9fc22e1aa93d0ff63483b6 || :
cp %{_builddir}/vendor/matchit/LICENSE.httprouter %{buildroot}/usr/share/package-licenses/netavark/e0b06b4bbfdf1ffba0edaaf4aefb22922df8561e || :
cp %{_builddir}/vendor/memchr/COPYING %{buildroot}/usr/share/package-licenses/netavark/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/vendor/memchr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/vendor/memchr/UNLICENSE %{buildroot}/usr/share/package-licenses/netavark/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/vendor/memoffset-0.7.1/LICENSE %{buildroot}/usr/share/package-licenses/netavark/02bf11a87b9bbacedf2fcf4856af3b933faef82e || :
cp %{_builddir}/vendor/mime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/mime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/0bc96c09b4b9635b10d73949dd06e92f22193c04 || :
cp %{_builddir}/vendor/mio/LICENSE %{buildroot}/usr/share/package-licenses/netavark/27541df8e6d877c3912bbe4c48711f36e826cc5b || :
cp %{_builddir}/vendor/mozim/LICENSE %{buildroot}/usr/share/package-licenses/netavark/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/vendor/mptcp-pm/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/bebecee44e7243ae0c5e0971cd4492ba1a19e5cd || :
cp %{_builddir}/vendor/multimap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/multimap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/512f61f7fe734aa8f08ede10a9ccd51826d6ea06 || :
cp %{_builddir}/vendor/netlink-packet-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/bebecee44e7243ae0c5e0971cd4492ba1a19e5cd || :
cp %{_builddir}/vendor/netlink-packet-generic/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/bebecee44e7243ae0c5e0971cd4492ba1a19e5cd || :
cp %{_builddir}/vendor/netlink-packet-route-0.19.0/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/bebecee44e7243ae0c5e0971cd4492ba1a19e5cd || :
cp %{_builddir}/vendor/netlink-packet-route/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/bebecee44e7243ae0c5e0971cd4492ba1a19e5cd || :
cp %{_builddir}/vendor/netlink-packet-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/bebecee44e7243ae0c5e0971cd4492ba1a19e5cd || :
cp %{_builddir}/vendor/netlink-proto/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/bebecee44e7243ae0c5e0971cd4492ba1a19e5cd || :
cp %{_builddir}/vendor/netlink-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/bebecee44e7243ae0c5e0971cd4492ba1a19e5cd || :
cp %{_builddir}/vendor/nftables/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/vendor/nftables/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/a4cce4109410f6a357e762a1c2c7a937d4fa21b2 || :
cp %{_builddir}/vendor/nftables/resources/test/nft/NOTICE %{buildroot}/usr/share/package-licenses/netavark/ca9c3d8b1f9e11464d5051a8b1ea5a6a517044d5 || :
cp %{_builddir}/vendor/nix-0.26.4/LICENSE %{buildroot}/usr/share/package-licenses/netavark/a6fe1503554eb18138838c526d150f58fc104133 || :
cp %{_builddir}/vendor/nix-0.27.1/LICENSE %{buildroot}/usr/share/package-licenses/netavark/a6fe1503554eb18138838c526d150f58fc104133 || :
cp %{_builddir}/vendor/nix/LICENSE %{buildroot}/usr/share/package-licenses/netavark/a6fe1503554eb18138838c526d150f58fc104133 || :
cp %{_builddir}/vendor/num-traits/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/num-traits/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/vendor/num_cpus/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/num_cpus/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ec9737a4e769cce48d5c95d9c75a4ba5f29a2563 || :
cp %{_builddir}/vendor/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/ordered-float/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/108bb98fdf8f27765ea240d80481be8362175ca7 || :
cp %{_builddir}/vendor/ordered-stream/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/ordered-stream/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/parking/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/parking/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/paste/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/paste/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/percent-encoding/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/percent-encoding/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/a81399b7c3ec2d4619848fd59c11d21211fc3b86 || :
cp %{_builddir}/vendor/petgraph/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/petgraph/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/vendor/pin-project-internal/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/vendor/pin-project-internal/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/pin-project-lite/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/vendor/pin-project-lite/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/pin-project/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/vendor/pin-project/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/pin-utils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/a2f60339450a52e61c6c1e27dc44bd1e671ad28e || :
cp %{_builddir}/vendor/pin-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/91abce61ea0c1c313bb5ba31f04196490960a479 || :
cp %{_builddir}/vendor/piper/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/piper/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/polling-2.8.0/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/aca374a3362a76702c50bd4e7d590a57f8834fc7 || :
cp %{_builddir}/vendor/polling-2.8.0/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/96c0ace4eb1b0a78134d978d3c6d656a860a670f || :
cp %{_builddir}/vendor/ppv-lite86/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/088830dcb78eba1a2052df69bd5cba5445e8f2d7 || :
cp %{_builddir}/vendor/ppv-lite86/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/e1c86f32641f01a5b85d6e9b20138e8470b883fc || :
cp %{_builddir}/vendor/prettyplease/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/prettyplease/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/proc-macro-crate/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/1d47c63586fe3be7f228cff1ab0c029b53741875 || :
cp %{_builddir}/vendor/proc-macro-crate/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/prost-build/LICENSE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/prost-derive/LICENSE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/prost-types/LICENSE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/rand/COPYRIGHT %{buildroot}/usr/share/package-licenses/netavark/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/vendor/rand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/4632a631b427f005d97734ea8c6a44090fec5cd9 || :
cp %{_builddir}/vendor/rand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/vendor/rand_chacha/COPYRIGHT %{buildroot}/usr/share/package-licenses/netavark/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/vendor/rand_chacha/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/vendor/rand_chacha/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/vendor/rand_core/COPYRIGHT %{buildroot}/usr/share/package-licenses/netavark/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/vendor/rand_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/vendor/regex-automata/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/regex-automata/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/vendor/regex-syntax/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/regex-syntax/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/vendor/regex-syntax/src/unicode_tables/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/netavark/68d12a03b339648117165b9c021b93f26974d6f6 || :
cp %{_builddir}/vendor/regex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/regex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/vendor/rtnetlink/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/bebecee44e7243ae0c5e0971cd4492ba1a19e5cd || :
cp %{_builddir}/vendor/rustix-0.37.27/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/rustix-0.37.27/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/netavark/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/vendor/rustix-0.37.27/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/rustix/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/rustix/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/netavark/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/vendor/rustix/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/rustversion/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/rustversion/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/ryu/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/ryu/LICENSE-BOOST %{buildroot}/usr/share/package-licenses/netavark/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/vendor/same-file/COPYING %{buildroot}/usr/share/package-licenses/netavark/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/vendor/same-file/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/2ad1215c12bd0a3492399dc438aa63084323c662 || :
cp %{_builddir}/vendor/same-file/UNLICENSE %{buildroot}/usr/share/package-licenses/netavark/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/vendor/serde-value/COPYING %{buildroot}/usr/share/package-licenses/netavark/fb56a0a55d46380208e2912508618a623e5ddeff || :
cp %{_builddir}/vendor/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/serde_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/serde_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/serde_json/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/serde_json/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/serde_path_to_error/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/serde_path_to_error/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/serde_repr/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/serde_repr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/sha1/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/422e6fd980775f9997ed6735c28a14ad20c222e8 || :
cp %{_builddir}/vendor/sha1/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/1741e5596832e62cd0791301fc9dcf4b9d0bc2c9 || :
cp %{_builddir}/vendor/sha2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/422e6fd980775f9997ed6735c28a14ad20c222e8 || :
cp %{_builddir}/vendor/sha2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/1741e5596832e62cd0791301fc9dcf4b9d0bc2c9 || :
cp %{_builddir}/vendor/signal-hook-registry/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/signal-hook-registry/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/8e31d76c1073644a6e761836ac34a590fee47a83 || :
cp %{_builddir}/vendor/slab/LICENSE %{buildroot}/usr/share/package-licenses/netavark/96f019e8abadc7a87b330a697504d874a1c06268 || :
cp %{_builddir}/vendor/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/c61640f6c218caf86d1b8072e09668a8362dba04 || :
cp %{_builddir}/vendor/socket2-0.4.10/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/socket2-0.4.10/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/vendor/socket2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/socket2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/vendor/static_assertions/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/vendor/static_assertions/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/972723ef8f594b1c7515e4c227ff9d5912041fac || :
cp %{_builddir}/vendor/strsim/LICENSE %{buildroot}/usr/share/package-licenses/netavark/f5feee4154156527645a9b18ef29da23fc859ca9 || :
cp %{_builddir}/vendor/strum/LICENSE %{buildroot}/usr/share/package-licenses/netavark/967573fc64a706430e19b4942fe728870c8182f8 || :
cp %{_builddir}/vendor/strum_macros/LICENSE %{buildroot}/usr/share/package-licenses/netavark/967573fc64a706430e19b4942fe728870c8182f8 || :
cp %{_builddir}/vendor/syn-1.0.109/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/syn-1.0.109/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/sync_wrapper/LICENSE %{buildroot}/usr/share/package-licenses/netavark/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/vendor/sysctl/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/113ef81b9b6ef59c88b073449bcdec7faba6e57a || :
cp %{_builddir}/vendor/tempfile/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/tempfile/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/70693ba8757c4a17af68e39ab32e4e0d4a389416 || :
cp %{_builddir}/vendor/thiserror-impl/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/thiserror-impl/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/thiserror/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/thiserror/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/tinyvec/LICENSE-APACHE.md %{buildroot}/usr/share/package-licenses/netavark/47b573e3824cd5e02a1a3ae99e2735b49e0256e4 || :
cp %{_builddir}/vendor/tinyvec/LICENSE-MIT.md %{buildroot}/usr/share/package-licenses/netavark/ee70bf5efb387a6c52c0f5cbea4122c6a74a57bb || :
cp %{_builddir}/vendor/tinyvec/LICENSE-ZLIB.md %{buildroot}/usr/share/package-licenses/netavark/59b5efd50c4508e7fa74828e7469187bbe5bd864 || :
cp %{_builddir}/vendor/tinyvec_macros/LICENSE-APACHE.md %{buildroot}/usr/share/package-licenses/netavark/8cc042e8e4b82c5532c72172a1988a74a599d4b5 || :
cp %{_builddir}/vendor/tinyvec_macros/LICENSE-MIT.md %{buildroot}/usr/share/package-licenses/netavark/86d193cb6b24df990cbbaf67c6a24fddbcb574c1 || :
cp %{_builddir}/vendor/tokio-io-timeout/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/tokio-io-timeout/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/564b4c2883cfa949f9ca4e12a7a32abccfb5256e || :
cp %{_builddir}/vendor/tokio-macros/LICENSE %{buildroot}/usr/share/package-licenses/netavark/91b0ae81a1609fbc63e6ee539106bd0ce9f7e56a || :
cp %{_builddir}/vendor/tokio-stream/LICENSE %{buildroot}/usr/share/package-licenses/netavark/9e4ed0e5d74379ec227eefa28c8fbf66c964cf13 || :
cp %{_builddir}/vendor/tokio-util/LICENSE %{buildroot}/usr/share/package-licenses/netavark/9e4ed0e5d74379ec227eefa28c8fbf66c964cf13 || :
cp %{_builddir}/vendor/tokio/LICENSE %{buildroot}/usr/share/package-licenses/netavark/9e4ed0e5d74379ec227eefa28c8fbf66c964cf13 || :
cp %{_builddir}/vendor/toml_datetime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/toml_datetime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/vendor/toml_edit/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/toml_edit/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/vendor/tonic-build/LICENSE %{buildroot}/usr/share/package-licenses/netavark/35bfae8b4923ce07823233aabd23c10e189fcd49 || :
cp %{_builddir}/vendor/tonic/LICENSE %{buildroot}/usr/share/package-licenses/netavark/35bfae8b4923ce07823233aabd23c10e189fcd49 || :
cp %{_builddir}/vendor/tower-layer/LICENSE %{buildroot}/usr/share/package-licenses/netavark/e91bf1be869de7307c2165260d999f8316d92b8c || :
cp %{_builddir}/vendor/tower-service/LICENSE %{buildroot}/usr/share/package-licenses/netavark/e91bf1be869de7307c2165260d999f8316d92b8c || :
cp %{_builddir}/vendor/tower/LICENSE %{buildroot}/usr/share/package-licenses/netavark/e91bf1be869de7307c2165260d999f8316d92b8c || :
cp %{_builddir}/vendor/tracing-attributes/LICENSE %{buildroot}/usr/share/package-licenses/netavark/3c8e7847ca19c2bb00f4100c725810c04a1b56d6 || :
cp %{_builddir}/vendor/tracing-core/LICENSE %{buildroot}/usr/share/package-licenses/netavark/3c8e7847ca19c2bb00f4100c725810c04a1b56d6 || :
cp %{_builddir}/vendor/tracing-core/src/spin/LICENSE %{buildroot}/usr/share/package-licenses/netavark/0956f8ac49e23a546fb113f711d7cdc0c3e98c85 || :
cp %{_builddir}/vendor/tracing/LICENSE %{buildroot}/usr/share/package-licenses/netavark/3c8e7847ca19c2bb00f4100c725810c04a1b56d6 || :
cp %{_builddir}/vendor/trust-dns-proto/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/vendor/trust-dns-proto/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/c71b43677c4ac8205f6eb573a073ea8e6df60c91 || :
cp %{_builddir}/vendor/try-lock/LICENSE %{buildroot}/usr/share/package-licenses/netavark/69a8a8cb1ffcf1cc77de729dc0f830066465c7ec || :
cp %{_builddir}/vendor/typenum/LICENSE %{buildroot}/usr/share/package-licenses/netavark/481e4be7d70c11ee3f6e04a59a0e5afccc551db2 || :
cp %{_builddir}/vendor/typenum/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/69facfd64b2a7aa4a22c917ef10cd96e41b75b87 || :
cp %{_builddir}/vendor/typenum/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/5984f5244c7bc13bf15a5bea823c04ec0bbc714f || :
cp %{_builddir}/vendor/unicode-bidi/COPYRIGHT %{buildroot}/usr/share/package-licenses/netavark/871b9912ab96cf7d79cb8ae83ca0b08cd5d0cbfd || :
cp %{_builddir}/vendor/unicode-bidi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/unicode-bidi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/vendor/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/netavark/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/vendor/unicode-normalization/COPYRIGHT %{buildroot}/usr/share/package-licenses/netavark/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/vendor/unicode-normalization/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/unicode-normalization/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/vendor/url/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/url/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/a81399b7c3ec2d4619848fd59c11d21211fc3b86 || :
cp %{_builddir}/vendor/utf8parse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/vendor/utf8parse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/93074692b8a28bef1743c44a9e5b97b1401c0d09 || :
cp %{_builddir}/vendor/version_check/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/version_check/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/cfcb552ef0afbe7ccb4128891c0de00685988a4b || :
cp %{_builddir}/vendor/waker-fn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/vendor/waker-fn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/walkdir/COPYING %{buildroot}/usr/share/package-licenses/netavark/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/vendor/walkdir/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/vendor/walkdir/UNLICENSE %{buildroot}/usr/share/package-licenses/netavark/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/vendor/want/LICENSE %{buildroot}/usr/share/package-licenses/netavark/e9b66aefa3fef917a79b26ebc576b8e8e969a4e8 || :
cp %{_builddir}/vendor/winnow/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/c0955b5351b1dcafdd0b9bb2d7e84fe0e3d731ca || :
cp %{_builddir}/vendor/xdg-home/LICENSE %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/xdg-home/LICENSE-MIT %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/zbus/LICENSE %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/zbus_macros/LICENSE %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/zbus_names/LICENSE %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/zvariant/LICENSE %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/zvariant_derive/LICENSE %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/vendor/zvariant_utils/LICENSE %{buildroot}/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files libexec
%defattr(-,root,root,-)
/usr/libexec/podman/netavark

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/netavark/02bf11a87b9bbacedf2fcf4856af3b933faef82e
/usr/share/package-licenses/netavark/067f31555f328efb78075174add7db97d98618c6
/usr/share/package-licenses/netavark/072741b191e599c01d8136fd14030bdcdb906e62
/usr/share/package-licenses/netavark/088830dcb78eba1a2052df69bd5cba5445e8f2d7
/usr/share/package-licenses/netavark/0956f8ac49e23a546fb113f711d7cdc0c3e98c85
/usr/share/package-licenses/netavark/0af21fe114d277c00d6ec7fba71f83fc03275b0a
/usr/share/package-licenses/netavark/0bc96c09b4b9635b10d73949dd06e92f22193c04
/usr/share/package-licenses/netavark/0c160db99de1b5577d1160540f1a1312b01a3f5b
/usr/share/package-licenses/netavark/108bb98fdf8f27765ea240d80481be8362175ca7
/usr/share/package-licenses/netavark/113ef81b9b6ef59c88b073449bcdec7faba6e57a
/usr/share/package-licenses/netavark/144111aa0f14ef5a181326683aa9ebbd9252bca6
/usr/share/package-licenses/netavark/1726596c1cc6c65d3a272abc337b13936430cf96
/usr/share/package-licenses/netavark/1741e5596832e62cd0791301fc9dcf4b9d0bc2c9
/usr/share/package-licenses/netavark/1b0e913d41a66c988376898aa995d6c2f45bb50c
/usr/share/package-licenses/netavark/1d47c63586fe3be7f228cff1ab0c029b53741875
/usr/share/package-licenses/netavark/1de935a6c7ea6a2196a49062d498cb04a7f5baea
/usr/share/package-licenses/netavark/1ed710abaa8e6f1039a65ee19db6b19804514a75
/usr/share/package-licenses/netavark/246a6a647fc03a8acf28b902ab37764142bc0c9c
/usr/share/package-licenses/netavark/2510927d07430a2092720e8f4a5287043f75e8d3
/usr/share/package-licenses/netavark/27541df8e6d877c3912bbe4c48711f36e826cc5b
/usr/share/package-licenses/netavark/2ad1215c12bd0a3492399dc438aa63084323c662
/usr/share/package-licenses/netavark/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/netavark/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84
/usr/share/package-licenses/netavark/2df5d31b2f1da55a1d251084b2b47afe37eb9dde
/usr/share/package-licenses/netavark/3175cda277cf92d21d9adbacdcfbf53a02c78890
/usr/share/package-licenses/netavark/3389b1fc45edfdd16c95926164ecf61e8369c9d8
/usr/share/package-licenses/netavark/35bfae8b4923ce07823233aabd23c10e189fcd49
/usr/share/package-licenses/netavark/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/netavark/388871ab0ab7f8ba6aaa0d444a5153f15c918cdb
/usr/share/package-licenses/netavark/39806df76979277073594a0c19005c3c7fb17221
/usr/share/package-licenses/netavark/3a86cfdfa553511b381388859c9e94ce9e1f916b
/usr/share/package-licenses/netavark/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/netavark/3c8e7847ca19c2bb00f4100c725810c04a1b56d6
/usr/share/package-licenses/netavark/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/netavark/422e6fd980775f9997ed6735c28a14ad20c222e8
/usr/share/package-licenses/netavark/4632a631b427f005d97734ea8c6a44090fec5cd9
/usr/share/package-licenses/netavark/47b573e3824cd5e02a1a3ae99e2735b49e0256e4
/usr/share/package-licenses/netavark/481e4be7d70c11ee3f6e04a59a0e5afccc551db2
/usr/share/package-licenses/netavark/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/netavark/4dbe8833d0189c691b308c3dd40fab84ef2e9630
/usr/share/package-licenses/netavark/4f399d285a128de165a3adb6319e7c85d2a9e297
/usr/share/package-licenses/netavark/4f8ab673f6e2ae6c7bb2910d7f38838c18c12178
/usr/share/package-licenses/netavark/50121d8b8c9f6483fe17ea679f28f85fe59b2a5a
/usr/share/package-licenses/netavark/512f61f7fe734aa8f08ede10a9ccd51826d6ea06
/usr/share/package-licenses/netavark/564b4c2883cfa949f9ca4e12a7a32abccfb5256e
/usr/share/package-licenses/netavark/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/netavark/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/netavark/58853eb8199b5afe72a73a25fd8cf8c94285174b
/usr/share/package-licenses/netavark/5984f5244c7bc13bf15a5bea823c04ec0bbc714f
/usr/share/package-licenses/netavark/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/netavark/59b5efd50c4508e7fa74828e7469187bbe5bd864
/usr/share/package-licenses/netavark/5ed53061419caf64f84d064f3641392a2a10fa7f
/usr/share/package-licenses/netavark/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/netavark/64a8c11fd0f3068e743bfc681bcbef4f50a6b779
/usr/share/package-licenses/netavark/669a1e53b9dd9df3474300d3d959bb85bad75945
/usr/share/package-licenses/netavark/68d12a03b339648117165b9c021b93f26974d6f6
/usr/share/package-licenses/netavark/69a8a8cb1ffcf1cc77de729dc0f830066465c7ec
/usr/share/package-licenses/netavark/69facfd64b2a7aa4a22c917ef10cd96e41b75b87
/usr/share/package-licenses/netavark/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/netavark/70693ba8757c4a17af68e39ab32e4e0d4a389416
/usr/share/package-licenses/netavark/709be9d07c00197f2e96593f4cd84f975c4e9f5f
/usr/share/package-licenses/netavark/738188f5fed28a950b0fede659706238ec35f8bb
/usr/share/package-licenses/netavark/7963d112b803d110d3e75e932c052284fd208629
/usr/share/package-licenses/netavark/7a842f34e127456338641b14c7a00ec246d89fb6
/usr/share/package-licenses/netavark/7c85e3e83cb61889208968604b387fbd188d49c7
/usr/share/package-licenses/netavark/7ca2c807379211b3ca6b04f10723088ca423c4fe
/usr/share/package-licenses/netavark/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/netavark/7e5936a6fa3cf3518c01cec41345adf27399fe12
/usr/share/package-licenses/netavark/84da196f153d2d4e6a9fc22e1aa93d0ff63483b6
/usr/share/package-licenses/netavark/86d193cb6b24df990cbbaf67c6a24fddbcb574c1
/usr/share/package-licenses/netavark/871b9912ab96cf7d79cb8ae83ca0b08cd5d0cbfd
/usr/share/package-licenses/netavark/8aa7ac03b16828b3c2263f4d760a779a32d5dd2a
/usr/share/package-licenses/netavark/8cc042e8e4b82c5532c72172a1988a74a599d4b5
/usr/share/package-licenses/netavark/8e31d76c1073644a6e761836ac34a590fee47a83
/usr/share/package-licenses/netavark/8e73926030e5cf210703bbdbd4d5c2a3880b3f71
/usr/share/package-licenses/netavark/8e75077dab38548245db65153967207be8c3ce88
/usr/share/package-licenses/netavark/8fe88f09d35c6054e0a780a793833c16fb888168
/usr/share/package-licenses/netavark/90b909b5333c24d88b46437677e159fb35e56fad
/usr/share/package-licenses/netavark/91abce61ea0c1c313bb5ba31f04196490960a479
/usr/share/package-licenses/netavark/91b0ae81a1609fbc63e6ee539106bd0ce9f7e56a
/usr/share/package-licenses/netavark/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/netavark/93074692b8a28bef1743c44a9e5b97b1401c0d09
/usr/share/package-licenses/netavark/967573fc64a706430e19b4942fe728870c8182f8
/usr/share/package-licenses/netavark/96c0ace4eb1b0a78134d978d3c6d656a860a670f
/usr/share/package-licenses/netavark/96f019e8abadc7a87b330a697504d874a1c06268
/usr/share/package-licenses/netavark/972723ef8f594b1c7515e4c227ff9d5912041fac
/usr/share/package-licenses/netavark/9c6e81caeb170dd5501d39895df9efb657c3c86b
/usr/share/package-licenses/netavark/9e4ed0e5d74379ec227eefa28c8fbf66c964cf13
/usr/share/package-licenses/netavark/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/netavark/a2e7dc468fde32fb02ccb9417b5bad304836e267
/usr/share/package-licenses/netavark/a2f60339450a52e61c6c1e27dc44bd1e671ad28e
/usr/share/package-licenses/netavark/a3164f0a981565d3d4dbedfbba23fec2bf387a7e
/usr/share/package-licenses/netavark/a4cce4109410f6a357e762a1c2c7a937d4fa21b2
/usr/share/package-licenses/netavark/a6fe1503554eb18138838c526d150f58fc104133
/usr/share/package-licenses/netavark/a74c5e048f9ed570eb892f81ca5daf05936475b0
/usr/share/package-licenses/netavark/a81399b7c3ec2d4619848fd59c11d21211fc3b86
/usr/share/package-licenses/netavark/aca18f6eebf597377e59fff1f0e6adbadcdcf97b
/usr/share/package-licenses/netavark/aca374a3362a76702c50bd4e7d590a57f8834fc7
/usr/share/package-licenses/netavark/b716916e6b0b96af5ecadf1eaee25f966f5d6cb2
/usr/share/package-licenses/netavark/b916da18877fcec3d37860fe60c1189c447e90b9
/usr/share/package-licenses/netavark/b95542c0be3bd915a1e7d8df80711fce5cd0795b
/usr/share/package-licenses/netavark/bb7a734916fe2261aa2b805e19a75838d557af9d
/usr/share/package-licenses/netavark/bb92c62835916e922667b4fe181beed0e6efca91
/usr/share/package-licenses/netavark/bebecee44e7243ae0c5e0971cd4492ba1a19e5cd
/usr/share/package-licenses/netavark/c0955b5351b1dcafdd0b9bb2d7e84fe0e3d731ca
/usr/share/package-licenses/netavark/c145b1a607ecf06aed81f1d04a65c2e43dffdc63
/usr/share/package-licenses/netavark/c371f0a7cbb203643d88566665a452f96bf1ab86
/usr/share/package-licenses/netavark/c5880598f02535f99de9ec3436bf8b59ce893bc7
/usr/share/package-licenses/netavark/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/netavark/c71b43677c4ac8205f6eb573a073ea8e6df60c91
/usr/share/package-licenses/netavark/c8eef3d34d69b1d62fd378fa02150a0bce62fd26
/usr/share/package-licenses/netavark/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a
/usr/share/package-licenses/netavark/ca9c3d8b1f9e11464d5051a8b1ea5a6a517044d5
/usr/share/package-licenses/netavark/cb74eb831db08b7fe98f84b59c9bda195e5a3588
/usr/share/package-licenses/netavark/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/netavark/cfcb552ef0afbe7ccb4128891c0de00685988a4b
/usr/share/package-licenses/netavark/d3f4001d9de83a122956c9195d73e2507bf6c533
/usr/share/package-licenses/netavark/d74ad13f1402c35008f22bc588a6b8199ed164d3
/usr/share/package-licenses/netavark/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/netavark/e0b06b4bbfdf1ffba0edaaf4aefb22922df8561e
/usr/share/package-licenses/netavark/e1c86f32641f01a5b85d6e9b20138e8470b883fc
/usr/share/package-licenses/netavark/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/netavark/e81567c196622efa36b46c5fd53cde741aaf0993
/usr/share/package-licenses/netavark/e91bf1be869de7307c2165260d999f8316d92b8c
/usr/share/package-licenses/netavark/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
/usr/share/package-licenses/netavark/e9b66aefa3fef917a79b26ebc576b8e8e969a4e8
/usr/share/package-licenses/netavark/ebc84230d16898593f0c90479ac9ee5576d7cc65
/usr/share/package-licenses/netavark/ec9737a4e769cce48d5c95d9c75a4ba5f29a2563
/usr/share/package-licenses/netavark/ee70bf5efb387a6c52c0f5cbea4122c6a74a57bb
/usr/share/package-licenses/netavark/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/netavark/f14afa20edce530124d39cd56312c7781c19b267
/usr/share/package-licenses/netavark/f516ded20090880b5bb281ad2f9dde3d94e9e369
/usr/share/package-licenses/netavark/f5feee4154156527645a9b18ef29da23fc859ca9
/usr/share/package-licenses/netavark/f8cc03f90ea18587a80a23486a64f129260a3034
/usr/share/package-licenses/netavark/f911b0506e6ba6a56b4edac717b461799f380ef0
/usr/share/package-licenses/netavark/fa284d19a6ac85562019f93110d4338e53de654b
/usr/share/package-licenses/netavark/fb56a0a55d46380208e2912508618a623e5ddeff
/usr/share/package-licenses/netavark/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
/usr/share/package-licenses/netavark/ff432d95fdfee3587e45abd61685c2209d245901
/usr/share/package-licenses/netavark/ff44b187892fcf1cd15a3ca61b498041b28afecc

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/netavark.1

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/netavark-dhcp-proxy.service
/usr/lib/systemd/system/netavark-dhcp-proxy.socket
/usr/lib/systemd/system/netavark-firewalld-reload.service
